### ISSUE TITLE
Final Checks and Documentation

### ISSUE THREAD

**Issue by bettybhzhou** [UBC-MDS/InstaRF#24]
You have adequately documented:

- [x] package README (including usage and installation instructions)
- [x] functions
- [x] tests
- [x] vignette (for R packages only)

**Comment by bettybhzhou** [comment]
Package dependences:
   testthat,
    InstaRF,
    knitr,
    rmarkdown,
    png,
    spatialfil,
    testit,
    covr

**Comment by bettybhzhou** [comment]
Reza, please include TA comment from proposal: 
A quick google scan showed several packages that have similar image processing functionality (e.g. spatstat has its own Gaussian blur function). There's nothing wrong with this, you are encouraged to make your own versions of existing functions! Just please note in subsequent milestones.

**Comment by reza-bagheri** [comment]
Readme file updated
